spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/how2java?useUnicode=true&useSSL=false&characterEncoding=utf8
  mvc:
    view:
      prefix: /web-inf/jsp/
      suffix: .jsp
logging:
  level:
    com.example.springboot: info
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 0
    timeout: 3000